"""
BIST (Borsa Istanbul) - Yahoo Finance'den 10 Yıllık Veri Çekici
Sütunlar: Popen, Phigh, Plow, Pclose, Vlot

Incremental mod:
  - Mevcut market_db.parquet varsa en erken tarihten geriye doğru eksik veriyi çeker
  - Zaten var olan tarihleri tekrar çekmez
  - Sonunda market_db.parquet'i long-format olarak günceller (Minerva uyumlu)
"""

import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import os

# ─── Ayarlar ──────────────────────────────────────────────────────────────────

END_DATE   = "2026-04-17"
START_DATE = (datetime.strptime(END_DATE, "%Y-%m-%d") - timedelta(days=10 * 365)).strftime("%Y-%m-%d")

OUTPUT_DIR = "data"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# BIST'te işlem gören hisseler için Yahoo Finance suffix: .IS
# Aşağıya istediğin sembolleri ekleyebilirsin
TICKERS = [
    "XU100.IS",   # BIST 100 endeksi
    "THYAO.IS",   # Türk Hava Yolları
    "GARAN.IS",   # Garanti BBVA
    "ASELS.IS",   # Aselsan
    "EREGL.IS",   # Ereğli Demir Çelik
    "KCHOL.IS",   # Koç Holding
    "SAHOL.IS",   # Sabancı Holding
    "SISE.IS",    # Şişe Cam
    "TOASO.IS",   # Tofaş
    "AKBNK.IS",   # Akbank
    "YKBNK.IS",   # Yapı Kredi
    "BIMAS.IS",   # BİM Mağazaları
    "FROTO.IS",   # Ford Otosan
    "PGSUS.IS",   # Pegasus
    "TAVHL.IS",   # TAV Havalimanları
    "ADESE.IS",
    "ADLVY.IS",
    "ADGYO.IS",
    "AFYON.IS",
    "AGHOL.IS",
    "AGESA.IS",
    "AGROT.IS",
    "AAGYO.IS",
    "AHSGY.IS",
    "AHGAZ.IS",
    "AKSFA.IS",
    "AKFK.IS",
    "AKM.IS",
    "AKMEN.IS",
    "AKCVR.IS",
    "AKBNK.IS",
    "AKCNS.IS",
    "AKDFA.IS",
    "AKYHO.IS",
    "AKENR.IS",
    "AKFGY.IS",
    "AKFIS.IS",
    "AKFYE.IS",
    "AKHAN.IS",
    "ATEKS.IS",
    "AKSGY.IS",
    "AKMGY.IS",
    "AKSA.IS",
    "AKSEN.IS",
    "AKGRT.IS",
    "AKSUE.IS",
    "AKTVK.IS",
    "AFB.IS",
    "AKTIF.IS",
    "ALCAR.IS",
    "ALGYO.IS",
    "ALARK.IS",
    "ALBRK.IS",
    "ALK.IS",
    "ALCTL.IS",
    "ALFAS.IS",
    "ALJF.IS",
    "ALKIM.IS",
    "ALKA.IS",
    "ALNUS.IS",
    "ANC.IS",
    "AYCES.IS",
    "ALTNY.IS",
    "ALKLC.IS",
    "ALVES.IS",
    "ANSGR.IS",
    "AEFES.IS",
    "ANHYT.IS",
    "ASUZU.IS",
    "ANGEN.IS",
    "ANELE.IS",
    "ARCLK.IS",
    "ARDYZ.IS",
    "ARENA.IS",
    "ARFYE.IS",
    "ARMGD.IS",
    "ARSAN.IS",
    "ARSVY.IS",
    "ARTMS.IS",
    "ARZUM.IS",
    "ASGYO.IS",
    "ASELS.IS",
    "ASTOR.IS",
    "ATAGY.IS",
    "ATATR.IS",
    "ATAVK.IS",
    "ATA.IS",
    "ATAYM.IS",
    "ATAKP.IS",
    "AGYO.IS",
    "ATLFA.IS",
    "ATSYH.IS",
    "ATLAS.IS",
    "ATATP.IS",
    "AVOD.IS",
    "AVGYO.IS",
    "AVTUR.IS",
    "AVHOL.IS",
    "AVPGY.IS",
    "AYDEM.IS",
    "AYEN.IS",
    "AYES.IS",
    "AYGAZ.IS",
    "AZTEK.IS",
    "A1CAP.IS",
    "ACP.IS",
    "A1YEN.IS",
    "BAGFS.IS",
    "BAHKM.IS",
    "BAKAB.IS",
    "BALAT.IS",
    "BALSU.IS",
    "BNTAS.IS",
    "BANVT.IS",
    "BARMA.IS",
    "BSRFK.IS",
    "BASGZ.IS",
    "BASCM.IS",
    "BEGYO.IS",
    "BTCIM.IS",
    "BSOKE.IS",
    "BYDNR.IS",
    "BAYRK.IS",
    "BERA.IS",
    "BRKT.IS",
    "BRKSN.IS",
    "BESLR.IS",
    "BESTE.IS",
    "BJKAS.IS",
    "BEYAZ.IS",
    "BIENY.IS",
    "BIGTK.IS",
    "BLCYT.IS",
    "BLKOM.IS",
    "BIMAS.IS",
    "BINBN.IS",
    "BIOEN.IS",
    "BRKVY.IS",
    "BRKO.IS",
    "BIGEN.IS",
    "BRLSM.IS",
    "BRMEN.IS",
    "BIZIM.IS",
    "BLUME.IS",
    "BMSTL.IS",
    "BMSCH.IS",
    "BNPPI.IS",
    "BOBET.IS",
    "BORSK.IS",
    "BORLS.IS",
    "BRSAN.IS",
    "BRYAT.IS",
    "BFREN.IS",
    "BOSSA.IS",
    "BRISA.IS",
    "BULGS.IS",
    "BLS.IS",
    "BLSMD.IS",
    "BURCE.IS",
    "BURVA.IS",
    "BRGAN.IS",
    "BUR.IS",
    "BRGFK.IS",
    "BUCIM.IS",
    "BVSAN.IS",
    "BIGCH.IS",
    "CRFSA.IS",
    "CASA.IS",
    "CEMZY.IS",
    "CEOEM.IS",
    "CCOLA.IS",
    "CONSE.IS",
    "COSMO.IS",
    "CRDFA.IS",
    "CVKMD.IS",
    "CWENE.IS",
    "CGCAM.IS",
    "CAGFA.IS",
    "CMSAN.IS",
    "CANTE.IS",
    "CATES.IS",
    "CLEBI.IS",
    "CELHA.IS",
    "CLKMT.IS",
    "CEMAS.IS",
    "CEMTS.IS",
    "CMBTN.IS",
    "CMENT.IS",
    "CIMSA.IS",
    "CUSAN.IS",
    "DVRLK.IS",
    "DYBNK.IS",
    "DAGI.IS",
    "DAPGM.IS",
    "DARDL.IS",
    "DGATE.IS",
    "DCTTR.IS",
    "DGRVK.IS",
    "DMSAS.IS",
    "DENVA.IS",
    "DENGE.IS",
    "DNZEN.IS",
    "DENFA.IS",
    "DZGYO.IS",
    "DERIM.IS",
    "DERHL.IS",
    "DESA.IS",
    "DESPC.IS",
    "DSTKF.IS",
    "DMD.IS",
    "DSYAT.IS",
    "DEVA.IS",
    "DNISI.IS",
    "DIRIT.IS",
    "DITAS.IS",
    "DKVRL.IS",
    "DMRGD.IS",
    "DOCO.IS",
    "DOFRB.IS",
    "DOFER.IS",
    "DOHOL.IS",
    "DGNMO.IS",
    "DOGVY.IS",
    "ARASE.IS",
    "DOGUB.IS",
    "DGGYO.IS",
    "DOAS.IS",
    "DFKTR.IS",
    "DOKTA.IS",
    "DURDO.IS",
    "DURKN.IS",
    "DUNYH.IS",
    "DNYVA.IS",
    "DYOBY.IS",
    "EBEBK.IS",
    "ECOGR.IS",
    "ECZYT.IS",
    "EDATA.IS",
    "EDIP.IS",
    "EFOR.IS",
    "EGEEN.IS",
    "EGGUB.IS",
    "EGPRO.IS",
    "EGSER.IS",
    "EPLAS.IS",
    "EGEGY.IS",
    "ECZIP.IS",
    "ECILC.IS",
    "EKER.IS",
    "EKIZ.IS",
    "EKOFA.IS",
    "EKOS.IS",
    "EKSUN.IS",
    "ELITE.IS",
    "EMKEL.IS",
    "EMNIS.IS",
    "EMIRV.IS",
    "EKTVK.IS",
    "DMLKT.IS",
    "EKGYO.IS",
    "EMVAR.IS",
    "EMPAE.IS",
    "ENDAE.IS",
    "ENJSA.IS",
    "ENERY.IS",
    "ENKAI.IS",
    "ENPRA.IS",
    "ENSRI.IS",
    "ERBOS.IS",
    "ERCB.IS",
    "EREGL.IS",
    "ERGLI.IS",
    "KIMMR.IS",
    "ERSU.IS",
    "ESCAR.IS",
    "ESCOM.IS",
    "ESEN.IS",
    "ETILR.IS",
    "EUKYO.IS",
    "EUYO.IS",
    "ETYAT.IS",
    "EUHOL.IS",
    "TEZOL.IS",
    "EUREN.IS",
    "EUPWR.IS",
    "EYGYO.IS",
    "FADE.IS",
    "FMIZP.IS",
    "FENER.IS",
    "FBB.IS",
    "FBBNK.IS",
    "FKPET.IS",
    "FLAP.IS",
    "FONET.IS",
    "FROTO.IS",
    "FORMT.IS",
    "FRMPL.IS",
    "FORTE.IS",
    "FRIGO.IS",
    "FZLGY.IS",
    "GWIND.IS",
    "GSRAY.IS",
    "GARFA.IS",
    "GARFL.IS",
    "GRNYO.IS",
    "GATEG.IS",
    "GEDIK.IS",
    "GEDZA.IS",
    "GLCVY.IS",
    "GENIL.IS",
    "GENTS.IS",
    "GENKM.IS",
    "GEREL.IS",
    "GZNMI.IS",
    "GIPTA.IS",
    "GMTAS.IS",
    "GESAN.IS",
    "GLB.IS",
    "GLBMD.IS",
    "GLYHO.IS",
    "GGBVK.IS",
    "GSIPD.IS",
    "GOODY.IS",
    "GOKNR.IS",
    "GOLTS.IS",
    "GOZDE.IS",
    "GRTHO.IS",
    "GSDDE.IS",
    "GSDHO.IS",
    "GUBRF.IS",
    "GLRYH.IS",
    "GLRMK.IS",
    "GUNDG.IS",
    "GRSEL.IS",
    "SAHOL.IS",
    "HALKF.IS",
    "HLGYO.IS",
    "HLVKS.IS",
    "HALKI.IS",
    "HLY.IS",
    "HRKET.IS",
    "HATEK.IS",
    "HATSN.IS",
    "HAYVK.IS",
    "HDFFL.IS",
    "HDFGS.IS",
    "HEDEF.IS",
    "HDFVK.IS",
    "HDFYB.IS",
    "HYB.IS",
    "HEKTS.IS",
    "HKTM.IS",
    "HTTBT.IS",
    "HOROZ.IS",
    "HUBVC.IS",
    "HUNER.IS",
    "HUZFA.IS",
    "HURGZ.IS",
    "ENTRA.IS",
    "ICB.IS",
    "ICBCT.IS",
    "ICUGS.IS",
    "INGRM.IS",
    "INVEO.IS",
    "IAZ.IS",
    "INVAZ.IS",
    "INVES.IS",
    "ISKPL.IS",
    "IEYHO.IS",
    "IDGYO.IS",
    "IHEVA.IS",
    "IHLGM.IS",
    "IHGZT.IS",
    "IHAAS.IS",
    "IHLAS.IS",
    "IHYAY.IS",
    "IMASM.IS",
    "INDES.IS",
    "INFO.IS",
    "IYF.IS",
    "INTEK.IS",
    "INTEM.IS",
    "ISDMR.IS",
    "ISTFK.IS",
    "ISTVY.IS",
    "ISFAK.IS",
    "ISFIN.IS",
    "ISGYO.IS",
    "ISGSY.IS",
    "ISMEN.IS",
    "IYM.IS",
    "ISYAT.IS",
    "ISBIR.IS",
    "ISSEN.IS",
    "IZINV.IS",
    "IZENR.IS",
    "IZMDC.IS",
    "IZFAS.IS",
    "JANTS.IS",
    "KFEIN.IS",
    "KLKIM.IS",
    "KLSER.IS",
    "KLVKS.IS",
    "KLYPV.IS",
    "KTEST.IS",
    "KAPLM.IS",
    "KRDMA.IS",
    "KRDMB.IS",
    "KRDMD.IS",
    "KAREL.IS",
    "KARSN.IS",
    "KRTEK.IS",
    "KARTN.IS",
    "KATVK.IS",
    "KTLEV.IS",
    "KATMR.IS",
    "KFILO.IS",
    "KAYSE.IS",
    "KNTFA.IS",
    "KENT.IS",
    "KRVGD.IS",
    "KERVN.IS",
    "TCKRC.IS",
    "KZBGY.IS",
    "KLGYO.IS",
    "KLRHO.IS",
    "KMPUR.IS",
    "KLMSN.IS",
    "KCAER.IS",
    "KOCFN.IS",
    "KCHOL.IS",
    "KOCMT.IS",
    "KSFIN.IS",
    "KLSYN.IS",
    "KNFRT.IS",
    "KONTR.IS",
    "KONYA.IS",
    "KONKA.IS",
    "KGYO.IS",
    "KORDS.IS",
    "KRPLS.IS",
    "KORTS.IS",
    "KOTON.IS",
    "KOPOL.IS",
    "KRGYO.IS",
    "KRSTL.IS",
    "KRONT.IS",
    "KTKVK.IS",
    "KTSVK.IS",
    "KSTUR.IS",
    "KUVVA.IS",
    "KUYAS.IS",
    "KBORU.IS",
    "KZGYO.IS",
    "KUTPO.IS",
    "KTSKR.IS",
    "LIDER.IS",
    "LIDFA.IS",
    "LILAK.IS",
    "LMKDC.IS",
    "LINK.IS",
    "LOGO.IS",
    "LKMNH.IS",
    "LRSHO.IS",
    "LXGYO.IS",
    "LUKSK.IS",
    "LYDHO.IS",
    "LYDYE.IS",
    "MACKO.IS",
    "MAKIM.IS",
    "MAKTK.IS",
    "MANAS.IS",
    "MRBAS.IS",
    "MRS.IS",
    "MAGEN.IS",
    "MRMAG.IS",
    "MARKA.IS",
    "MARMR.IS",
    "MAALT.IS",
    "MRSHL.IS",
    "MRGYO.IS",
    "MARTI.IS",
    "MTRKS.IS",
    "MAVI.IS",
    "MZHLD.IS",
    "MEDTR.IS",
    "MEGMT.IS",
    "MEGAP.IS",
    "MEKAG.IS",
    "MEKMD.IS",
    "MSA.IS",
    "MNDRS.IS",
    "MEPET.IS",
    "MERCN.IS",
    "MRBKF.IS",
    "MBFTR.IS",
    "MERIT.IS",
    "MERKO.IS",
    "METRO.IS",
    "MTRYO.IS",
    "MCARD.IS",
    "MEYSU.IS",
    "MHRGY.IS",
    "MIATK.IS",
    "MDASM.IS",
    "MDS.IS",
    "MGROS.IS",
    "MINTF.IS",
    "MSGYO.IS",
    "MSY.IS",
    "MSYBN.IS",
    "MPARK.IS",
    "MMCAS.IS",
    "MNGFA.IS",
    "MOBTL.IS",
    "MOGAN.IS",
    "MNDTR.IS",
    "MOPAS.IS",
    "EGEPO.IS",
    "NATEN.IS",
    "NTGAZ.IS",
    "NTHOL.IS",
    "NETAS.IS",
    "NETCD.IS",
    "NIBAS.IS",
    "NUHCM.IS",
    "NUGYO.IS",
    "NURVK.IS",
    "NRBNK.IS",
    "NYB.IS",
    "OBAMS.IS",
    "OBASE.IS",
    "ODAS.IS",
    "ODINE.IS",
    "OFSYM.IS",
    "ONCSM.IS",
    "ONRYT.IS",
    "OPET.IS",
    "ORCAY.IS",
    "ORFIN.IS",
    "ORGE.IS",
    "ORMA.IS",
    "OSVKS.IS",
    "OMD.IS",
    "OSMEN.IS",
    "OSTIM.IS",
    "OTKAR.IS",
    "OTOKC.IS",
    "OTOSR.IS",
    "OTTO.IS",
    "OYAKC.IS",
    "OYA.IS",
    "OYYAT.IS",
    "OYAYO.IS",
    "OYLUM.IS",
    "OZKGY.IS",
    "OZATD.IS",
    "OZGYO.IS",
    "OZRDN.IS",
    "OZSUB.IS",
    "OZYSR.IS",
    "PAMEL.IS",
    "PNLSN.IS",
    "PAGYO.IS",
    "PAPIL.IS",
    "PRFFK.IS",
    "PRDGS.IS",
    "PRKME.IS",
    "PARSN.IS",
    "PBT.IS",
    "PBTR.IS",
    "PASEU.IS",
    "PSGYO.IS",
    "PAHOL.IS",
    "PATEK.IS",
    "PCILT.IS",
    "PGSUS.IS",
    "PEKGY.IS",
    "PENGD.IS",
    "PENTA.IS",
    "PSDTC.IS",
    "PETKM.IS",
    "PKENT.IS",
    "PETUN.IS",
    "PINSU.IS",
    "PNSUT.IS",
    "PKART.IS",
    "PLTUR.IS",
    "POLHO.IS",
    "POLTK.IS",
    "PRZMA.IS",
    "QFINF.IS",
    "QYATB.IS",
    "YBQ.IS",
    "QYHOL.IS",
    "FIN.IS",
    "QNBTR.IS",
    "QNBFF.IS",
    "QNBFK.IS",
    "QNBVK.IS",
    "QUAGR.IS",
    "QUFIN.IS",
    "RNPOL.IS",
    "RALYH.IS",
    "RAYSG.IS",
    "REEDR.IS",
    "RYGYO.IS",
    "RYSAS.IS",
    "RODRG.IS",
    "ROYAL.IS",
    "RGYAS.IS",
    "RTALB.IS",
    "RUBNS.IS",
    "RUZYE.IS",
    "SAFKR.IS",
    "SANEL.IS",
    "SNICA.IS",
    "SANFM.IS",
    "SANKO.IS",
    "SAMAT.IS",
    "SARKY.IS",
    "SASA.IS",
    "SVGYO.IS",
    "SAYAS.IS",
    "SDTTR.IS",
    "SEGMN.IS",
    "SEKUR.IS",
    "SELEC.IS",
    "SELVA.IS",
    "SERNT.IS",
    "SRVGY.IS",
    "SEYKM.IS",
    "SILVR.IS",
    "SNGYO.IS",
    "SKYLP.IS",
    "SMRTG.IS",
    "SMART.IS",
    "SODSN.IS",
    "SOKE.IS",
    "SKTAS.IS",
    "SONME.IS",
    "SNPAM.IS",
    "SUMAS.IS",
    "SUNTK.IS",
    "SURGY.IS",
    "SUWEN.IS",
    "SMRFA.IS",
    "SMRVA.IS",
    "SEKFK.IS",
    "SEGYO.IS",
    "SKY.IS",
    "SKYMD.IS",
    "SEK.IS",
    "SKBNK.IS",
    "SOKM.IS",
    "TABGD.IS",
    "TAC.IS",
    "TCRYT.IS",
    "TAMFA.IS",
    "TNZTP.IS",
    "TARKM.IS",
    "TATGD.IS",
    "TATEN.IS",
    "TAVHL.IS",
    "DRPHN.IS",
    "TEBFA.IS",
    "TEKTU.IS",
    "TKFEN.IS",
    "TKNSA.IS",
    "TMPOL.IS",
    "TRHOL.IS",
    "TEVKS.IS",
    "TAE.IS",
    "TRBNK.IS",
    "TERA.IS",
    "TRA.IS",
    "TEHOL.IS",
    "TFNVK.IS",
    "TGSAS.IS",
    "TIMUR.IS",
    "TRYKI.IS",
    "TOASO.IS",
    "TRGYO.IS",
    "TRMET.IS",
    "TRENJ.IS",
    "TLMAN.IS",
    "TSPOR.IS",
    "TDGYO.IS",
    "TRMEN.IS",
    "TVM.IS",
    "TSGYO.IS",
    "TUCLK.IS",
    "TUKAS.IS",
    "TRCAS.IS",
    "TUREX.IS",
    "MARBL.IS",
    "TRKFN.IS",
    "TRILC.IS",
    "TCELL.IS",
    "TRKNT.IS",
    "TMSN.IS",
    "TUPRS.IS",
    "TRALT.IS",
    "THYAO.IS",
    "PRKAB.IS",
    "TTKOM.IS",
    "TTRAK.IS",
    "TBORG.IS",
    "TURGG.IS",
    "GARAN.IS",
    "TGB.IS",
    "HALKB.IS",
    "THL.IS",
    "EXIMB.IS",
    "THR.IS",
    "ISATR.IS",
    "ISBTR.IS",
    "ISCTR.IS",
    "ISKUR.IS",
    "TIB.IS",
    "KLN.IS",
    "KLNMA.IS",
    "TSK.IS",
    "TSKB.IS",
    "TURSG.IS",
    "SISE.IS",
    "TVB.IS",
    "VAKBN.IS",
    "TV8TV.IS",
    "UFUK.IS",
    "ULAS.IS",
    "ULUFA.IS",
    "ULUSE.IS",
    "ULUUN.IS",
    "UMPAS.IS",
    "USAK.IS",
    "UCAYM.IS",
    "ULKER.IS",
    "UNLU.IS",
    "VAKFA.IS",
    "VAKFN.IS",
    "VKGYO.IS",
    "VKFYO.IS",
    "VAKVK.IS",
    "VAKKO.IS",
    "VANGD.IS",
    "VBTYZ.IS",
    "VDFLO.IS",
    "VRGYO.IS",
    "VERUS.IS",
    "VERTU.IS",
    "VESBE.IS",
    "VESTL.IS",
    "VKING.IS",
    "VSNMD.IS",
    "VDFAS.IS",
    "YKFKT.IS",
    "YKFIN.IS",
    "YKR.IS",
    "YKYAT.IS",
    "YKB.IS",
    "YKBNK.IS",
    "YAPRK.IS",
    "YATAS.IS",
    "YYLGD.IS",
    "YAYLA.IS",
    "YGGYO.IS",
    "YEOTK.IS",
    "YYAPI.IS",
    "YESIL.IS",
    "YBTAS.IS",
    "YIGIT.IS",
    "YONGA.IS",
    "YKSLN.IS",
    "YUNSA.IS",
    "ZGYO.IS",
    "ZEDUR.IS",
    "ZERGY.IS",
    "ZRGYO.IS",
    "ZKBVK.IS",
    "ZKBVR.IS",
    "ZOREN.IS",
    "BINHO.IS",
]

# ─── Veri Çekme ───────────────────────────────────────────────────────────────

def rename_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Yahoo Finance sütunlarını proje terminolojisine çevirir."""
    col_map = {
        "Open":   "Popen",
        "High":   "Phigh",
        "Low":    "Plow",
        "Close":  "Pclose",
        "Volume": "Vlot",
    }
    df = df.rename(columns=col_map)
    # Sadece ilgili sütunları tut
    keep = [c for c in ["Popen", "Phigh", "Plow", "Pclose", "Vlot"] if c in df.columns]
    return df[keep]




MARKET_DB_PATH = os.path.join(OUTPUT_DIR, "market_db.parquet")


def load_existing() -> pd.DataFrame:
    """Mevcut market_db.parquet'i yükle. Yoksa boş DataFrame döndür."""
    if os.path.exists(MARKET_DB_PATH):
        df = pd.read_parquet(MARKET_DB_PATH)
        df["Date"] = pd.to_datetime(df["Date"])
        print(f"✅ Mevcut veri yüklendi: {len(df):,} satır "
              f"({df['Date'].min().date()} → {df['Date'].max().date()}, "
              f"{df['Ticker'].nunique()} hisse)")
        return df
    return pd.DataFrame()


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Mevcut veriyi yükle ───────────────────────────────────────────────────
    existing = load_existing()

    # Eksik tarih aralığını hesapla
    if not existing.empty:
        existing_min = existing["Date"].min()
        fetch_end = (existing_min - timedelta(days=1)).strftime("%Y-%m-%d")
        fetch_start = START_DATE
        if fetch_start >= fetch_end:
            print(f"\n✅ Veri zaten {START_DATE}'dan itibaren mevcut. Çekilecek yeni veri yok.")
            print(f"   Mevcut aralık: {existing['Date'].min().date()} → {existing['Date'].max().date()}")
            return
        print(f"\n📥 Eksik dönem çekilecek: {fetch_start} → {fetch_end}")
    else:
        fetch_start = START_DATE
        fetch_end   = END_DATE
        print(f"\n📥 Tüm dönem çekilecek: {fetch_start} → {fetch_end}")

    # ── Sembolleri çek ───────────────────────────────────────────────────────
    # Duplikatları kaldır
    unique_tickers = list(dict.fromkeys(TICKERS))
    new_frames = []
    ok_count = 0
    fail_count = 0

    print(f"\n{len(unique_tickers)} sembol işlenecek...\n")

    for i, symbol in enumerate(unique_tickers):
        ticker_clean = symbol.replace(".IS", "")
        df = fetch_ticker_range(symbol, fetch_start, fetch_end)
        if df is not None and not df.empty:
            df = df.reset_index()
            df["Ticker"] = ticker_clean
            df = df[["Date", "Ticker", "Popen", "Phigh", "Plow", "Pclose", "Vlot"]]
            new_frames.append(df)
            ok_count += 1
            if (i + 1) % 50 == 0:
                print(f"  [{i+1}/{len(unique_tickers)}] {ok_count} başarılı, {fail_count} başarısız")
        else:
            fail_count += 1

    print(f"\n✅ Çekim tamamlandı: {ok_count} sembol, {fail_count} başarısız")

    if not new_frames:
        print("[!] Yeni veri çekilemedi.")
        return

    # ── Yeni veriyi birleştir ─────────────────────────────────────────────────
    new_df = pd.concat(new_frames, ignore_index=True)
    new_df["Date"] = pd.to_datetime(new_df["Date"])

    if not existing.empty:
        # Mevcut verinin Ticker formatını kontrol et (.IS suffix'i kaldır)
        if existing["Ticker"].str.contains(".IS").any():
            existing["Ticker"] = existing["Ticker"].str.replace(".IS", "", regex=False)
        combined = pd.concat([new_df, existing], ignore_index=True)
    else:
        combined = new_df

    # Duplikat satırları kaldır (aynı Ticker+Date)
    combined = combined.drop_duplicates(subset=["Ticker", "Date"])
    combined = combined.sort_values(["Ticker", "Date"]).reset_index(drop=True)

    # Pvwap ekle (app.py ile tutarlı)
    if "Pvwap" not in combined.columns:
        combined["Pvwap"] = (combined["Phigh"] + combined["Plow"] + combined["Pclose"]) / 3

    # ── Kaydet ────────────────────────────────────────────────────────────────
    combined.to_parquet(MARKET_DB_PATH, index=False)

    print(f"\n{'─'*55}")
    print(f"📦 market_db.parquet güncellendi")
    print(f"   Toplam satır  : {len(combined):,}")
    print(f"   Toplam sembol : {combined['Ticker'].nunique()}")
    print(f"   Tarih aralığı : {combined['Date'].min().date()} → {combined['Date'].max().date()}")
    print(f"   Dosya         : {MARKET_DB_PATH}")
    print(f"{'─'*55}")


def fetch_ticker_range(symbol: str, start: str, end: str) -> pd.DataFrame | None:
    try:
        df = yf.download(
            symbol,
            start=start,
            end=end,
            auto_adjust=True,
            progress=False,
        )
        if df.empty:
            return None

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df = rename_columns(df)
        df.index.name = "Date"
        return df

    except Exception as e:
        return None


if __name__ == "__main__":
    main()
